/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import clases.*;
import javax.swing.JOptionPane;
import persistencia.ControlCajero;

/**
 *
 * @author edgar
 */
public class FrmRealizarRetiroT extends javax.swing.JFrame {
    private ControlCajero control;
    /**
     * Creates new form FrmRealizarRetiroT
     */
    public FrmRealizarRetiroT(ControlCajero cr) {
        initComponents();
        this.control= cr;
        ActualizarEstado();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        frmEstado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblComision = new javax.swing.JLabel();
        lblMontoFinal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxMonto = new javax.swing.JComboBox<>();
        btnRetiro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Realizar Retiro");

        btnSalir.setBackground(new java.awt.Color(65, 65, 65));
        btnSalir.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Cancalar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        frmEstado.setBackground(new java.awt.Color(65, 65, 65));

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Monto Actual");

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad de Retiro");

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Comisión");

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Monto Final");

        lblNombre.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");

        lblMonto.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(255, 255, 255));
        lblMonto.setText("Nombre");

        lblCantidad.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setText("Nombre");

        lblComision.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lblComision.setForeground(new java.awt.Color(255, 255, 255));
        lblComision.setText("Nombre");

        lblMontoFinal.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lblMontoFinal.setForeground(new java.awt.Color(255, 255, 255));
        lblMontoFinal.setText("Nombre");

        javax.swing.GroupLayout frmEstadoLayout = new javax.swing.GroupLayout(frmEstado);
        frmEstado.setLayout(frmEstadoLayout);
        frmEstadoLayout.setHorizontalGroup(
            frmEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmEstadoLayout.createSequentialGroup()
                .addGroup(frmEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmEstadoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(frmEstadoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(frmEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)))
                    .addGroup(frmEstadoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(frmEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addGap(40, 40, 40)
                .addGroup(frmEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComision, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMontoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        frmEstadoLayout.setVerticalGroup(
            frmEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmEstadoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(frmEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNombre))
                .addGap(26, 26, 26)
                .addGroup(frmEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblMonto))
                .addGap(29, 29, 29)
                .addGroup(frmEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(frmEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblComision))
                .addGap(26, 26, 26)
                .addGroup(frmEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblMontoFinal))
                .addGap(28, 28, 28))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Monto");

        cbxMonto.setBackground(new java.awt.Color(65, 65, 65));
        cbxMonto.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        cbxMonto.setForeground(new java.awt.Color(255, 255, 255));
        cbxMonto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "200", "400", "600", "800", "1000", "1200", "1400", "1600" }));
        cbxMonto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMontoItemStateChanged(evt);
            }
        });

        btnRetiro.setBackground(new java.awt.Color(74, 206, 74));
        btnRetiro.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnRetiro.setForeground(new java.awt.Color(0, 0, 0));
        btnRetiro.setText("Realizar Retiro");
        btnRetiro.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(22, 96, 22), new java.awt.Color(18, 91, 18)));
        btnRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(200, 200, 200))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(frmEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbxMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(frmEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(btnRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroActionPerformed
        // TODO add your handling code here:
        Cajero cj=control.getCajero();
        Tarjeta tar= cj.getTarjeta();
        if(control.VerificarDineroSistema(cj, Double.valueOf(String.valueOf(cbxMonto.getSelectedItem())))){
            if(control.ComprobarMontoUsuario(tar, Double.valueOf(String.valueOf(cbxMonto.getSelectedItem())))){
                if(control.HacerRetiro(cj, tar, Double.valueOf(String.valueOf(cbxMonto.getSelectedItem())))){
                    control.AgregarComision(cj, 21.00);
                    FrmReciboT frm=new FrmReciboT(control, Double.valueOf(String.valueOf(cbxMonto.getSelectedItem())), 21.00);
                    frm.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "No se Pudo Hacer el Retiro","Error!!!", JOptionPane.OK_OPTION);
                }
                
            }else{
                JOptionPane.showMessageDialog(this, "No Tienes Suficiente Dinero para Hacer Esta Acción","Error!!!", JOptionPane.OK_OPTION);
            }
        }else{
            JOptionPane.showMessageDialog(this, "No hay Suficiente Dinero en el Sistema","Error!!!", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnRetiroActionPerformed

    private void cbxMontoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMontoItemStateChanged
        // TODO add your handling code here:
        ActualizarEstado();
    }//GEN-LAST:event_cbxMontoItemStateChanged

    public void ActualizarEstado(){
        Cajero cj=control.getCajero();
        Tarjeta tar= cj.getTarjeta();
        Usuario user= tar.getUsuario();
        
        lblNombre.setText(user.getNombre());
        lblMonto.setText("$ "+String.valueOf(tar.getMonto()));
        lblCantidad.setText("$ "+String.valueOf(cbxMonto.getSelectedItem()));
        lblComision.setText("$ 21");
        double total= tar.getMonto()- Double.valueOf(String.valueOf(cbxMonto.getSelectedItem())) - 21.00;
        lblMontoFinal.setText("$ "+String.valueOf(total));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetiro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxMonto;
    private javax.swing.JPanel frmEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblComision;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblMontoFinal;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
